name: GitOps Pipeline

on:
  push:
    branches:
      - main

concurrency:
  # Forcing multiple conccurent runs of this workflow to be serialized
  # to avoid conflicts when updating the deployment manifest.
  group: ${{ github.workflow }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # required to push to ghcr

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to github container registry (ghcr)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOYMENT_REPO_PAT }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./src/Secrets.Demo.Api/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  update-deployment-manifest:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    env:
      # Target GitOps repository
      TARGET_REPO: hoangchu/secrets-demo-gitops
      TARGET_BRANCH: main
      MANIFEST_PATH: kubernetes/deployment.yaml

    permissions:
      # Requires write permission to commit and push changes to the target repo
      contents: write

    steps:
      - name: Checkout Deployment Repository (${{ env.TARGET_REPO }})
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          # NOTE: Requires a PAT with 'repo' scope access to the target repository
          token: ${{ secrets.DEPLOYMENT_REPO_PAT }}

      - name: Set Git Identity for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Deployment YAML Image Tag
        run: |
          sudo snap install yq
          yq e '.spec.template.spec.containers[0].image = "'"${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"'"' -i ${{ env.MANIFEST_PATH }}

      - name: Commit and Push Manifest Changes
        run: |
          if git diff --exit-code ${{ env.MANIFEST_PATH }}; then
            echo "No changes detected in deployment manifest. Skipping commit."
          else
            git add ${{ env.MANIFEST_PATH }}
            git commit -m "[CI] Bump secrets-demo image to ${{ github.sha }}"
            git push
          fi
